# Generated by Django 4.0.6 on 2022-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='title',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='firstname',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='lastname',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
