# Generated by Django 4.0.6 on 2022-07-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0003_alter_usermodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
