# Generated by Django 4.0.6 on 2022-07-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0005_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isAdmin',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newuser.usermodel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
