# Generated by Django 4.0.6 on 2022-07-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0011_remove_employee_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newuser.usermodel'),
        ),
    ]
